@startuml ALERP
top to bottom direction
skinparam packageStyle rectangle
actor 用户
actor 职员
actor 管理员
rectangle ERP {
  用户 -- (登录)
  用户 -- (修改密码)

  管理员 -- (用户管理)
  (用户管理) -- (新增用户)
  (用户管理) -- (修改用户)
  (用户管理) -- (删除用户)
  (用户管理) -- (用户权限管理)

  职员 -- (客户管理)
  (客户管理) -- (查看客户列表)
  (客户管理) -- (查看客户详情)
  (客户管理) -- (新增客户)
  (客户管理) -- (删除客户)
  (客户管理) -- (修改客户)

  职员 -- (入库单管理)
  (入库单管理) -- (查看入库单列表)
  (入库单管理) -- (查看入库单详情)
  (入库单管理) -- (新增入库单)
  (入库单管理) -- (废弃入库单)

  职员 -- (加工单管理)
  (加工单管理) -- (查看加工单列表)
  (加工单管理) -- (查看加工单详情)
  (加工单管理) -- (新增加工单)
  (加工单管理) -- (废弃加工单)

  职员 -- (出货单管理)
  (出货单管理) -- (查看出货单列表)
  (出货单管理) -- (查看出货单详情)
  (出货单管理) -- (新增出货单)
  (出货单管理) -- (废弃出货单)
  (出货单管理) -- (开具发票记录)
  (出货单管理) -- (打印出货单)
  
  职员 -- (收款单管理)
  (收款单管理) -- (查看收款单列表)
  (收款单管理) -- (查看收款单详情)
  (收款单管理) -- (编辑收款单)
  (收款单管理) -- (废弃收款单)
  (收款单管理) -- (添加收款记录)
  (收款单管理) -- (逾期提醒)

  职员 -- (查看汇总信息)
  (查看汇总信息) -- (欠款客户)
  (查看汇总信息) -- (收支记录)

  职员 -- (录入公司支出)

}
@enduml